version: '3.8'

services:
  todo_api:
    build: .
    restart: on-failure
    depends_on:
      todo_db:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@todo_db:${POSTGRES_PORT}/${POSTGRES_DB}
      - DEBUG=${DEBUG}
    ports:
      - "8000:8000"
    networks:
      - todo_network

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  todo_db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  postgres_data: